"""Regression tests against the behavior of the pre-refactor implementation.

``fixtures/golden_main_sync.json`` was generated by running the original
``CalendarSyncProcessor`` + strategies of ``main`` (commit 94badb6) on
``fixtures/scenario_events.json``: fresh/existing preferences for every sync
target, plus a ``--prune-before`` run. The refactored code must produce exactly
the same calendar mutations and the same preferences.

Preferences now live in one profile file, and exams are keyed by their name
rather than their full title: the legacy files are translated accordingly.
Managed events are tagged with a new property: the fixtures are translated as
if the target calendar had already been migrated (see ``test_planner`` for the
migration itself).
"""

from __future__ import annotations

import json
from datetime import date
from typing import Any

import pytest
from conftest import FakeCalendarGateway, load_fixture, save_profile, saved

from calendar_coloring.cli.main import run
from calendar_coloring.config import Config
from calendar_coloring.reporting import NullReporter
from calendar_coloring.sync.models import Mutation
from calendar_coloring.sync.planner import LEGACY_MANAGED_PROPERTIES, MANAGED_PROPERTY
from calendar_coloring.targets import SyncTarget
from calendar_coloring.workflow import SyncOptions


def with_current_tag(data: Any) -> Any:
    text = json.dumps(data)
    for legacy in LEGACY_MANAGED_PROPERTIES:
        text = text.replace(f'"{legacy}"', f'"{MANAGED_PROPERTY}"')
    return json.loads(text)


SCENARIO = with_current_tag(load_fixture("scenario_events.json"))
GOLDEN = with_current_tag(load_fixture("golden_main_sync.json"))


def as_legacy_operation(mutation: Mutation) -> dict[str, Any]:
    op: dict[str, Any] = {"action": mutation.action.value}
    if mutation.action.value != "insert":
        op["event_id"] = mutation.event_id
    if mutation.body is not None:
        op["body"] = mutation.body
    op["summary"] = mutation.summary
    return op


LEGACY_EXAM_PREFIX = "Esame: "
SECTIONS = {
    "courses": "course_colors.json",
    "exams": "exam_states.json",
    "deadlines": "deadline_colors.json",
}


def from_legacy_exams(exam_states: dict[str, Any]) -> dict[str, Any]:
    return {key.removeprefix(LEGACY_EXAM_PREFIX): v for key, v in exam_states.items()}


def expected_preferences(files_raw: dict[str, str | None]) -> dict[str, Any]:
    expected = {
        section: json.loads(files_raw[name] or "{}")
        for section, name in SECTIONS.items()
    }
    expected["exams"] = from_legacy_exams(expected["exams"])
    return expected


def setup(scenario: str, config: Config) -> tuple[SyncOptions, FakeCalendarGateway]:
    state, target, *flags = scenario.split("-")
    if state == "existing":
        existing = SCENARIO["existing_state"]
        save_profile(
            config,
            courses=existing["course_colors"],
            exams=from_legacy_exams(existing["exam_states"]),
            deadlines=existing["deadline_colors"],
        )
    prune_before = (
        date.fromisoformat(SCENARIO["prune_before"]) if "prune" in flags else None
    )
    options = SyncOptions(target=SyncTarget(target), prune_before=prune_before)
    gateway = FakeCalendarGateway(
        {"Src": SCENARIO["source"], "Tgt": SCENARIO["target"]}
    )
    return options, gateway


def snapshot(config: Config) -> dict[str, Any]:
    return {section: saved(config, section) for section in SECTIONS}


@pytest.mark.parametrize("scenario", sorted(GOLDEN))
def test_matches_legacy_behavior(scenario: str, config: Config) -> None:
    options, gateway = setup(scenario, config)

    exit_code = run(options, config, gateway, NullReporter())

    assert exit_code == 0
    expected = GOLDEN[scenario]
    actual_ops = [as_legacy_operation(m) for m in gateway.all_mutations]
    assert actual_ops == expected["mutations"]
    assert snapshot(config) == expected_preferences(expected["files_raw"])


@pytest.mark.parametrize("scenario", sorted(GOLDEN))
def test_second_run_is_a_no_op(scenario: str, config: Config) -> None:
    """After a sync, re-running must not change anything (idempotency)."""
    options, gateway = setup(scenario, config)
    run(options, config, gateway, NullReporter())
    files_after_first = snapshot(config)
    gateway.batches.clear()

    run(options, config, gateway, NullReporter())

    assert gateway.all_mutations == []
    assert snapshot(config) == files_after_first
