"""Regression tests against the behavior of the pre-refactor implementation.

``fixtures/golden_main_sync.json`` was generated by running the original
``CalendarSyncProcessor`` + strategies of ``main`` (commit 94badb6) on
``fixtures/scenario_events.json``: fresh/existing preferences for every sync
target, plus a ``--prune-before`` run. The refactored code must produce exactly
the same calendar mutations and the same preference files, byte for byte.
"""

from __future__ import annotations

import json
from datetime import date
from typing import Any

import pytest
from conftest import FakeCalendarGateway, load_fixture

from calendar_coloring.cli.main import run
from calendar_coloring.config import Config
from calendar_coloring.reporting import NullReporter
from calendar_coloring.sync.models import Mutation
from calendar_coloring.targets import SyncTarget
from calendar_coloring.workflow import SyncOptions

SCENARIO = load_fixture("scenario_events.json")
GOLDEN = load_fixture("golden_main_sync.json")


def as_legacy_operation(mutation: Mutation) -> dict[str, Any]:
    op: dict[str, Any] = {"action": mutation.action.value}
    if mutation.action.value != "insert":
        op["event_id"] = mutation.event_id
    if mutation.body is not None:
        op["body"] = mutation.body
    op["summary"] = mutation.summary
    return op


def state_files(config: Config) -> dict[str, Any]:
    return {
        "course_colors.json": config.course_colors_path,
        "exam_states.json": config.exam_states_path,
        "deadline_colors.json": config.deadline_colors_path,
    }


def setup(scenario: str, config: Config) -> tuple[SyncOptions, FakeCalendarGateway]:
    state, target, *flags = scenario.split("-")
    if state == "existing":
        existing = SCENARIO["existing_state"]
        config.course_colors_path.write_text(
            json.dumps(existing["course_colors"], indent=4)
        )
        config.exam_states_path.write_text(
            json.dumps(existing["exam_states"], indent=4)
        )
        config.deadline_colors_path.write_text(
            json.dumps(existing["deadline_colors"], indent=4)
        )
    prune_before = (
        date.fromisoformat(SCENARIO["prune_before"]) if "prune" in flags else None
    )
    options = SyncOptions(target=SyncTarget(target), prune_before=prune_before)
    gateway = FakeCalendarGateway(
        {"Src": SCENARIO["source"], "Tgt": SCENARIO["target"]}
    )
    return options, gateway


def snapshot(config: Config) -> dict[str, str | None]:
    return {
        name: path.read_text() if path.exists() else None
        for name, path in state_files(config).items()
    }


@pytest.mark.parametrize("scenario", sorted(GOLDEN))
def test_matches_legacy_behavior(scenario: str, config: Config) -> None:
    options, gateway = setup(scenario, config)

    exit_code = run(options, config, gateway, NullReporter())

    assert exit_code == 0
    expected = GOLDEN[scenario]
    actual_ops = [as_legacy_operation(m) for m in gateway.all_mutations]
    assert actual_ops == expected["mutations"]
    assert snapshot(config) == expected["files_raw"]


@pytest.mark.parametrize("scenario", sorted(GOLDEN))
def test_second_run_is_a_no_op(scenario: str, config: Config) -> None:
    """After a sync, re-running must not change anything (idempotency)."""
    options, gateway = setup(scenario, config)
    run(options, config, gateway, NullReporter())
    files_after_first = snapshot(config)
    gateway.batches.clear()

    run(options, config, gateway, NullReporter())

    assert gateway.all_mutations == []
    assert snapshot(config) == files_after_first
